### PR TITLE
Added support for user defined host UDP port and IP address

### PR DESCRIPTION
**Pull request by maszaa**
Fixes https://github.com/juliuscc/heos-api/issues/20

### CODE REVIEW

**Comment by juliuscc** [comment]
I appreciate the effort of not introducing any dependencies! This looks really good but I am not sure if this is the correct way to do this.

What are the advantages of using environmental variables over just adding function parameters? I would imagine that `exportDevices()` could have the following signature:

```typescript
export function discoverDevices(
	timeout: number = defaultTimeout,
	onDiscover: (address: string) => void,
	options: { localHost: string = '239.255.255.250', localPort: number = 1900 } = {},
	onTimeout?: (addresses: string[]) => void
): () => void {
	
	// ...

	return quit
}
```

Maybe this exact function signature is not perfect, mostly because it would require a major version update, but wouldn't something like this be easier to use? Especially as env-vars are not used any where else.

**Comment by maszaa** [comment]
That's an option also. Environment variables would provide separation between application code and user/host/client configuration. Then again one could define the options by environment variables in his/her own code.

I've been recently working so much with the end products so my mindset set was on how to provide configurable software. :)

**Comment by maszaa** [comment]
How about a solution like this:

```js
const defaultDiscoverOptions: DiscoverOptions = {
	localPort: 1900,
	localHost: null
}

// ...

export function discoverDevices(
	timeout: number = defaultTimeout,
	options: DiscoverOptions = defaultDiscoverOptions,
	onDiscover: (address: string) => void,
	onTimeout?: (addresses: string[]) => void
): () => void {
	const socket = createSocket('udp4')

	options.localHost ? socket.bind(options.localPort, options.localHost) : socket.bind(options.localPort)

	// ...
}

export function discoverOneDevice(timeout: number = defaultTimeout, options: DiscoverOptions = defaultDiscoverOptions): Promise<string> {
	return new Promise((resolve, reject) => {
		// ...
		const quit = discoverDevices(timeout, options, onDiscover, onTimeout)
	})
}
```

**Comment by juliuscc** [comment]
I agree that that is a good solution. I do however want to change two things.

1. The options parameter should be able to be used without specifying both port and host. Both values in the DiscoverOptions-type should be optional.

2. The method should be able to be used without specifying any options. Therefore the second parameter should be `onDiscover`. I do not know if options should be the third or last parameter. What do you think?

**Comment by maszaa** [comment]
1. Fixed
2. I set it as the fourth parameter. But I don't like that. Maybe the discover module could be implemented as a `class` in a next major version and allow either `onTimeout` or `options` or both via method overload. Another option could be defining types for `timeOut`, `onDiscover` and `onTimeout` inside `DiscoverOptions` type and using an object of type in question as a single parameter for discover functions.

**Comment by juliuscc** [comment]
Yes! That is a great Idea! I have been struggling with figuring out a good order all day. I think the best order is
1. onDiscover
2. onTimeout
3. options

Maybe change place on 2 and 3.

**Comment by juliuscc** [comment]
I just thought about another alternative that might be even simpler. What about not specifying a port or host? Then the operating system will attempt to bind to a random port. It will always get a free port.

**Comment by juliuscc** [comment]
I wrote and pushed a fix that should fix this. It worked on my machine. Does the new fix work for you?

**Comment by maszaa** [comment]
It does not as dgram still binds to a wrong network interface.

Just pushed a new commit based on https://github.com/juliuscc/heos-api/pull/21#issuecomment-499229908

**Comment by juliuscc** [comment]
Ah so if you choose the address the os knows which interface it should use? Then we should go back to the old plan with the exception of not specifying port. I still think that you should bind to a free port.

**Comment by maszaa** [comment]
I think it could be useful to be able to define the port too. But if no port is defined let dgram/OS decide.

**Comment by juliuscc** [comment]
Yes that is probably clever. You never know what use case will come in the future. Let’s change the order of the function parameters, and update the docs. Otherwise it looks good to go.

**Comment by maszaa** [comment]
I think more users will use `onTimeout` than `options`. By swapping them null/undefined should be passed as the third parameter if `onTimeout` is used. Therefore I would prefer

1. timeout
2. onDiscover
3. onTimeout
4. options

Are there some other doc than README? If not then it's up-to-date.

**Comment by juliuscc** [comment]
You have convinced me. Great that you have squashed the commits also!

I actually liked your idea of also having timeout in the options object so I suggest that we put that one there as well. Also the options object should in my opinion have a flat structure. Like:
```typescript
export type DiscoverOptions = {
	port?: number
	address?: string
	timeout?: number
} 
```

possibly:

```typescript
export type DiscoverOptions = {
	localPort?: number
	localAddress?: string
	timeout?: number
} 
```

... to be clear that it is not setting destionation-port/address

**Comment by juliuscc** [comment]
So the order should be:
1. onDiscover
2. onTimeout
3. options

**Comment by juliuscc** [comment]
I hope you are okay with me really wanting this to be very thought through. This would be a breaking change and I want it to really count 😁

**Comment by maszaa** [comment]
My changes weren't breaking ones 😉

`bindOptions` was there because that nested object could be casted to `dgram.BindOptions`. I also gave a thought for future use cases - there may be other options which aren't related to sockets.

**Comment by juliuscc** [comment]
I understood that now. I am not sure if I think it is a good idea to use bindOptions. Firstly there is no reason to expose the underlying implementation. Anyone should be able to use this library without having knowledge about how UDP works in node and maybe not even knowing that it UDP is used at all. We can expose our functionality in any way possible, and in a way that makes the most sense to the end user. Secondly I strongly feel that an options object should be one layer deep.

What are your thoughts? I really appreciate getting an alternative perspective, as I think this is the best for creating a good interface for this library.

I have commited what I think it should be like, but after your so we can revert if we want.

**Comment by maszaa** [comment]
That's a valid point also.

But with timeout moved to options I would go with

1. options
2. onDiscover
3. onTimeout

Maybe options could be `DiscoverOptions | number` and this wouldn't be a breaking change. What do you think? Ofc that would need some more checking.

**Comment by juliuscc** [comment]
Wow that was a great idea! Let’s do that!

**Comment by maszaa** [comment]
What do you think? I think it's good to go now.

**Comment by juliuscc** [comment]
This is great! Thanks! I want to add a couple of more tests, that test the overloading logic, but I think that could be added in a new pull request.

**Pull request merged**
